### ISSUE TITLE
mac docker运行报错，报错信息如下

### ISSUE THREAD

**Issue by wanroua** [Cl0udG0d/SZhe_Scan#15]
b53cfa67fd97        szhe_scan_web       "flask run"              2 minutes ago       Restarting (2) 50 seconds ago                                       szhe_scan_web_1

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

 * Serving Flask app "index.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Usage: flask run [OPTIONS]

Error: While importing "index", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/code/index.py", line 6, in <module>
    from Init import app, redispool
ModuleNotFoundError: No module named 'Init'

**Comment by Cl0udG0d** [comment]
今晚上检查了之后给你回复哈

**Comment by wanroua** [comment]
> 今晚上检查了之后给你回复哈

好的

**Comment by Cl0udG0d** [comment]
已修复，是有一个包的名字未修改，修改后在云服务器上已成功运行

**Comment by wanroua** [comment]
> 已修复，是有一个包的名字未修改，修改后在云服务器上已成功运行

 好的，我重新clone docker运行就OK了？

**Comment by Cl0udG0d** [comment]
是的，我删除旧的镜像，重新clone后，再运行就不会报错了

**Comment by wanroua** [comment]
> 是的，我删除旧的镜像，重新clone后，再运行就不会报错了

thinks
